### PR TITLE
Fld 'user.photo_url' set as optional (may be NULL)

### PR DESCRIPTION
**Pull request by stanislav-ostr**

### CODE REVIEW

**Comment by oleksandr-danylchenko** [comment]
Did you change the schema and migration without creating a new one?

**Comment by stanislav-ostr** [comment]
> Did you change the schema and migration without creating a new one?

Yes, minor changes

**Comment by stanislav-ostr** [comment]
Whould I create new migration?

**Comment by oleksandr-danylchenko** [comment]
> Should I create new migration?

Yes. Prisma forces us to create new migrations even for small changes. And we mustn't modify the existing ones. Because Prisma will throw the existing migration conflict error for other devs and won't process the changes

**Review by oleksandr-danylchenko — COMMENTED** [review]
Was the `yarn.lock` changed after the migration? Because I don't think that it should be included in this PR :slightly_smiling_face:

**Comment by stanislav-ostr** [comment]
I don't understand how it happened, I just ran yarn install:all

**Comment by stanislav-ostr** [comment]
ready

**Review by oleksandr-danylchenko — APPROVED** [review]
Thanks!

**Pull request merged**
