### PR TITLE
Connect top autoline to backend

### PR DESCRIPTION
**Pull request by R0ixy**
https://app.asana.com/0/1202525679663009/1202993559858706/f

### CODE REVIEW

**Review by o-rudych — CHANGES_REQUESTED** [review]
image

I think we should rename `Continuously variable transmission (CVT)` to `CVT` in our database.

**Comment by o-rudych** [comment]
Looks like you lost the descending order of cars when you refactored the backend.
Please check.

**Comment by iryb** [comment]
> I think we should rename Continuously variable transmission (CVT) to CVT in our database.

@o-rudych It will be in different pull request - either change option name in DB or fix card using styles (styles are preferable).

**Comment by o-rudych** [comment]
Sorting seems to work correctly now.

**Review by iryb — APPROVED** [review]

**Comment by iryb** [comment]
@o-rudych If everything works fine please approve this PR.

**Review by o-rudych — APPROVED** [review]

**Pull request merged**
