### PR TITLE
bug_41: Fix display of car card in 'New Cars' section (mobile layout)

### PR DESCRIPTION
**Pull request by stanislav-ostr**

### CODE REVIEW

**Review by Aleksandr-Shulha-dev — COMMENTED** [review]
If we remove the property "justify-items: center" for ".secondContainerCards", this bug disappears. I think the problem is this.

**Comment by Aleksandr-Shulha-dev** [comment]
https://gyazo.com/7f0f61c5b4c251b73d7b236ac66a8dce

**Comment by stanislav-ostr** [comment]
There is a requirement to place content in the center in the mobile version
Снимок экрана 2022-09-05 161659

**Comment by Aleksandr-Shulha-dev** [comment]
> There is a requirement to place content in the center in the mobile version Снимок экрана 2022-09-05 161659

This happens because the container has a right margin. The card width equals the width of the container if we delete "justify-items". In order for the cards to be in the center, you need to reduce margin rigth for container.

image

**Comment by oleksandr-danylchenko** [comment]
@Aleksandr-Shulha-dev @stanislav-ostr 
To center the content w/o flex you can specify right and left margins as `auto`. Or if you want to work with flex, try to use `flex: 1` on the card item. I'll prevents its shrinking to take just enough space to fit the content

**Pull request closed without merging**
