### PR TITLE
Search autos by characteristics

### PR DESCRIPTION
**Pull request by elador13**
See - https://app.asana.com/0/1202525679663009/1202720801120400/f

Screenshot_1
image
Screenshot_2

### Swap if user set min field higher, tnah max field
swap

image
image
image

### CODE REVIEW

**Comment by oleksandr-danylchenko** [comment]
Please use ONLY ENGLISH options and filters!

**Comment by oleksandr-danylchenko** [comment]
Do you use the `Lato` font everywhere? Or does the cyrillic look not that appealing with that font?
image

**Comment by elador13** [comment]
> Do you use the `Lato` font everywhere? Or does the cyrillic look not that appealing with that font? image

Yeah, it's probably because of cyrillic, I didn't change any fonts.

**Comment by oleksandr-danylchenko** [comment]
@elador13 
Could this PR be separated into 2? One for the simple and one for the advanced filters. 
Because it's quite mind-numbing to go through ~40 files focused

**Comment by oleksandr-danylchenko** [comment]
Or you can create 3 [stacked PRs](https://blog.logrocket.com/using-stacked-pull-requests-in-github/#:%7E:text=What%20are%20stacked%20pull%20requests,coherent%20units%20to%20represent%20changes.): 
1. backend endpoints PR
2. simple filter PR :arrow_up: 
3. advanced filter PR :arrow_up:

**Review by oleksandr-danylchenko — CHANGES_REQUESTED** [review]
@elador13 
Could this PR be separated into smaller ones? One for the simple and one for the advanced filters. 
Because it's quite mind-numbing to go through ~40 files focused.

You can create **3 [stacked PRs](https://blog.logrocket.com/using-stacked-pull-requests-in-github/#:%7E:text=What%20are%20stacked%20pull%20requests,coherent%20units%20to%20represent%20changes.)**: 
1. backend endpoints PR
2. simple filter PR :arrow_up: 
3. advanced filter PR :arrow_up:

**Pull request closed without merging**
